<a href="https://colab.research.google.com/github/Klaudia2022/Obliczenianaukowe/blob/main/Lab4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [16]:
#Zadanie 1
#Napisz metodę, która oblicz pole między osią OX, a wykresemfunkcji na danym przedziale za pomocą sum Riemanna (przbliżeń prostokątami). 
#Sprawdź jej działanie na wybranje przez siebie funkcji porównując z wynikiem całkowania symbolicznego.
#
# np.linspace(0,1,10) - podział odcinka 0,1 na 10 punktów

def calka(fun, a, b, N):
  if a>b:
    a,b=b,a
  podzial=np.linspace(a,b,N)
  sum=0
  for i in range(N-1):
    sum+=abs(fun(podzial[i]))*(b-a)/(N-1)
  return sum

calka(lambda x: -x**5,0,1,10000)

0.1666166658336664

In [22]:
#NumPy
tab=np.array([[1,2],[3,4],[4,1]])

In [26]:
tab.shape

(3, 2)

In [31]:
#Zadanie 3
tablica=np.array([[1,-1,2,-2],[3,-3,4,-4]])
tab2=np.array(tablica,dtype=float)
tab2

array([[ 1., -1.,  2., -2.],
       [ 3., -3.,  4., -4.]])

In [32]:
tab3=np.array([-1,0,1])

In [33]:
np.sqrt(tab3)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([nan,  0.,  1.])

In [38]:
tab4=tab3.astype(complex) #inny sposób na zmianę typów danych
tab4
np.sqrt(tab4).imag #wyciągamy części urojone
np.sqrt(tab4).real #yciągamy części rzeczywiste

array([0., 0., 1.])

In [39]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
np.meshgrid([1,2,3],['a','b','c'])

[array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]), array([['a', 'a', 'a'],
        ['b', 'b', 'b'],
        ['c', 'c', 'c']], dtype='<U1')]

In [52]:
#Zadanie 4
t1=np.ones((2,2))
t2=np.zeros((2,2))
t3=np.array(3)
t4=4*t1-2*np.eye((2))
from scipy.linalg import block_diag
Mat1=block_diag(t1,t2,t3,t4)
Mat1

array([[1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 0., 2., 4.],
       [0., 0., 0., 0., 0., 4., 2.]])

In [53]:
Mat2=block_diag(np.ones((2,2)),np.zeros((2,2)),3,(4*np.ones((2,2))-2*np.eye(2)))

In [54]:
Mat2

array([[1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 0., 2., 4.],
       [0., 0., 0., 0., 0., 4., 2.]])

In [55]:
Mat1[0,0]

1.0

In [56]:
Mat1[0,0]=3

In [57]:
Mat1

array([[3., 1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 0., 2., 4.],
       [0., 0., 0., 0., 0., 4., 2.]])

In [58]:
Mat1[1:3,::2]

array([[1., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [59]:
Mat1[:,::-1]

array([[0., 0., 0., 0., 0., 1., 3.],
       [0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0., 0.],
       [4., 2., 0., 0., 0., 0., 0.],
       [2., 4., 0., 0., 0., 0., 0.]])

In [64]:
Mat1

array([[3., 1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 0., 2., 4.],
       [0., 0., 0., 0., 0., 4., 2.]])

In [63]:
#Zadanie 5
Mat2=block_diag(Mat1[-3:,-3:],Mat1[:4,:4])
Mat2

array([[3., 0., 0., 0., 0., 0., 0.],
       [0., 2., 4., 0., 0., 0., 0.],
       [0., 4., 2., 0., 0., 0., 0.],
       [0., 0., 0., 3., 1., 0., 0.],
       [0., 0., 0., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [66]:
#Zadanie 6
Mat3=Mat1[1::2,1::2]
Mat3

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 2.]])