<a href="https://colab.research.google.com/github/Klaudia2022/Obliczenianaukowe/blob/main/lab5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from scipy.linalg import block_diag

In [2]:
Mat1=block_diag(np.ones((2,2)),np.zeros((2,2)),3,(4*np.ones((2,2))-2*np.eye(2)))

In [3]:
Mat1.shape

(7, 7)

In [9]:
Mat1.reshape((1,49))

array([[1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        3., 0., 0., 0., 0., 0., 0., 0., 2., 4., 0., 0., 0., 0., 0., 4.,
        2.]])

In [7]:
tab=np.array([[1,2,3],[4,5,6]])
tab

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
tab.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
tab.reshape((1,6))

array([[1, 2, 3, 4, 5, 6]])

In [11]:
tab.reshape(-1) #układa w tablicę 1 na odpowiednią liczbę kolumn

array([1, 2, 3, 4, 5, 6])

In [13]:
tablica=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
tablica.reshape((4,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [15]:
np.arange(1,17).reshape((4,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [82]:
#Zadanie
tab1=100*np.ones((5,6,3))
for i in range(5):
  for j in range(6):
    for k in range(3):
      tab1[i,j,k]+=60*i+10*j+300*k

tab1

array([[[100., 400., 700.],
        [110., 410., 710.],
        [120., 420., 720.],
        [130., 430., 730.],
        [140., 440., 740.],
        [150., 450., 750.]],

       [[160., 460., 760.],
        [170., 470., 770.],
        [180., 480., 780.],
        [190., 490., 790.],
        [200., 500., 800.],
        [210., 510., 810.]],

       [[220., 520., 820.],
        [230., 530., 830.],
        [240., 540., 840.],
        [250., 550., 850.],
        [260., 560., 860.],
        [270., 570., 870.]],

       [[280., 580., 880.],
        [290., 590., 890.],
        [300., 600., 900.],
        [310., 610., 910.],
        [320., 620., 920.],
        [330., 630., 930.]],

       [[340., 640., 940.],
        [350., 650., 950.],
        [360., 660., 960.],
        [370., 670., 970.],
        [380., 680., 980.],
        [390., 690., 990.]]])

In [46]:
t1=np.array([[1],[2]])
t2=np.array([[3,4]])
print(t1,t2)
tt=t1+t2

[[1]
 [2]] [[3 4]]


In [84]:
tablica1=np.arange(0,241,60).reshape((5,1,1))
tablica2=np.arange(0,51,10).reshape((1,6,1))
tablica3=np.arange(0,601,300).reshape((1,1,3))
tabl=tablica3+tablica2+tablica1
tabl

array([[[  0, 300, 600],
        [ 10, 310, 610],
        [ 20, 320, 620],
        [ 30, 330, 630],
        [ 40, 340, 640],
        [ 50, 350, 650]],

       [[ 60, 360, 660],
        [ 70, 370, 670],
        [ 80, 380, 680],
        [ 90, 390, 690],
        [100, 400, 700],
        [110, 410, 710]],

       [[120, 420, 720],
        [130, 430, 730],
        [140, 440, 740],
        [150, 450, 750],
        [160, 460, 760],
        [170, 470, 770]],

       [[180, 480, 780],
        [190, 490, 790],
        [200, 500, 800],
        [210, 510, 810],
        [220, 520, 820],
        [230, 530, 830]],

       [[240, 540, 840],
        [250, 550, 850],
        [260, 560, 860],
        [270, 570, 870],
        [280, 580, 880],
        [290, 590, 890]]])

In [36]:
t3=2*np.ones((2,2))
t4=3*np.eye(2)
t3**t4

array([[8., 1.],
       [1., 8.]])

In [39]:
A=np.arange(1,17).reshape(2,8)
A

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [40]:
A.T

array([[ 1,  9],
       [ 2, 10],
       [ 3, 11],
       [ 4, 12],
       [ 5, 13],
       [ 6, 14],
       [ 7, 15],
       [ 8, 16]])

In [42]:
B=np.arange(1,17)
B

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [45]:
B.T

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

#Agregacja


In [49]:
np.mean(A,axis=1)

array([ 4.5, 12.5])

In [50]:
L=np.random.random(100)

In [51]:
L

array([0.4755674 , 0.27262016, 0.82806737, 0.66376639, 0.91090528,
       0.90336965, 0.25553439, 0.38558228, 0.66411145, 0.35517946,
       0.20890979, 0.29016188, 0.23572831, 0.3371507 , 0.71864087,
       0.8493834 , 0.25968135, 0.26064554, 0.98053995, 0.2367993 ,
       0.56023643, 0.03469991, 0.85875675, 0.75645356, 0.21682663,
       0.53690077, 0.92745174, 0.35467218, 0.0755722 , 0.94038748,
       0.42649248, 0.51626511, 0.96045342, 0.36039297, 0.19278808,
       0.56210278, 0.01904459, 0.86869325, 0.68380286, 0.50882961,
       0.4660845 , 0.19803825, 0.15522976, 0.60083648, 0.25109194,
       0.30684227, 0.38658266, 0.4644579 , 0.91606473, 0.40357691,
       0.54292841, 0.62038769, 0.95454872, 0.08264246, 0.69415341,
       0.28179712, 0.80711396, 0.5962182 , 0.54459184, 0.67206568,
       0.45878796, 0.19059789, 0.29752739, 0.61022154, 0.67752552,
       0.98848764, 0.29285226, 0.10774335, 0.2553735 , 0.24572464,
       0.11159069, 0.57198697, 0.81307418, 0.70643843, 0.25638

In [52]:
np.sum(L)

48.28712333722851

In [55]:
np.var(L)

0.07621308234224482

In [57]:
np.cumsum(A, axis=1)    #axis do dodatkowy argument, który mówi nam po której osi mamy dodawać

array([[  1,   3,   6,  10,  15,  21,  28,  36],
       [  9,  19,  30,  42,  55,  69,  84, 100]])

In [58]:
A>5

array([[False, False, False, False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [59]:
A[A>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [60]:
A*(A>5)

array([[ 0,  0,  0,  0,  0,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [64]:
if np.all(A>5):
  print(10)

In [69]:
L=np.arange(1,17).reshape(4,4)
L

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [68]:
x=np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [70]:
y=np.array([0,4,1,16])
y

array([ 0,  4,  1, 16])

In [71]:
L[x<y]

array([[ 5,  6,  7,  8],
       [13, 14, 15, 16]])

In [72]:
x<y

array([False,  True, False,  True])

In [74]:
A=np.array([[2,3],[0,2]])
B=np.array([[2,5],[3,8]])
A,B

(array([[2, 3],
        [0, 2]]), array([[2, 5],
        [3, 8]]))

In [78]:
C=np.dot(np.dot(B,A),np.linalg.inv(B))
C

array([[-16.,  12.],
       [-27.,  20.]])

In [85]:
np.linalg.eig(A)

(array([2., 2.]), array([[ 1.00000000e+00, -1.00000000e+00],
        [ 0.00000000e+00,  1.48029737e-16]]))

In [86]:
np.linalg.eig(A)[0]

array([2., 2.])

In [92]:
np.linalg.eig(A)[1][:,0]

array([1., 0.])

In [94]:
np.linalg.eig(C)[0]

array([2.+3.41915903e-07j, 2.-3.41915903e-07j])